### PR TITLE
Move towards code generation

### PR DESCRIPTION
**Pull request by krlmlr**
~~This is incomplete, but hopefully shows where we're heading. Still to do:~~

- [x] Slightly prettier code
- [x] Only generate if input changes

Does it work for you? Are you open to repeating this pattern for the three other tests?

### CODE REVIEW

**Comment by krlmlr** [comment]
@rundel: I'm done here for now, awaiting your review.

410a93b497a0b98dc3dfd1cec7d062454a707baf didn't add a test, should it have? If it did, it would show up as a diff after merging main and regenerating the test files.

**Comment by krlmlr** [comment]
Some last changes to make `R CMD check` happy, and to align with your code style. Done now.

Thanks for your prompt responses! Can't wait to use it in fledge! Are you open to releasing a patch update to CRAN?

**Comment by krlmlr** [comment]
Would you like to do the three other tests yourself, or do you need a hand?

**Comment by rundel** [comment]
Just taking a look at this now - looks like a great solution and I should be able to port the other 3 over easily. Thanks for the suggestion and the working example.

**Pull request merged**
